Update test2-app.yaml

diff --git a/.github/workflows/test2-app.yaml b/.github/workflows/test2-app.yaml
--- a/.github/workflows/test2-app.yaml
+++ b/.github/workflows/test2-app.yaml
@@ -14,4 +14,4 @@ jobs:
 
     steps:
       - name: Run second test of App 
-        run: if [ $RANDOM -gt 20000 ]; then echo "I failed"; exit 1; else echo "I passed"; exit 0; fi
+        run: if [ $RANDOM -gt 60000 ]; then echo "I failed"; exit 1; else echo "I passed"; exit 0; fi
